#!/bin/bash
# =============================================================================
# GENERATED FILE — DO NOT EDIT
# Generated by scripts/generate.py from packages.yaml
# Re-generate with: python3 scripts/generate.py (or: make generate)
# =============================================================================
set -euo pipefail

FAILED_PACKAGES=()

log() {
    echo "==> $*"
}

warn() {
    echo "WARNING: $*" >&2
}

try_run() {
    local desc="$1"
    shift
    if ! "$@"; then
        warn "Failed to install: $desc"
        FAILED_PACKAGES+=("$desc")
    fi
}

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------
log "Updating system..."
sudo pacman -Syu --noconfirm

if ! command -v yay &> /dev/null; then
    log "Installing yay..."
    sudo pacman -S --noconfirm --needed git base-devel
    tmpdir="$(mktemp -d)"
    git clone https://aur.archlinux.org/yay.git "$tmpdir/yay"
    (cd "$tmpdir/yay" && makepkg -si --noconfirm)
    rm -rf "$tmpdir"
fi

install_core() {
    log "Installing core packages..."
    try_run "core (pacman)" sudo pacman -S --noconfirm --needed \
        wget \
        curl \
        git \
        stow \
        zsh \
        tmux \
        neovim \
        jq \
        yq \
        ripgrep \
        fzf \
        cmake \
        gnupg \
        unzip \
        rsync \
        tldr \
        btop \
        fastfetch \
        net-tools \
        ttl \
        tailscale \
        eza
    try_run "grex" yay -S --noconfirm --needed grex
    try_run "sipcalc" yay -S --noconfirm --needed sipcalc
    try_run "bitwarden-cli" yay -S --noconfirm --needed bitwarden-cli
    log "Installing oh-my-posh..."
    try_run "oh-my-posh" bash -c "curl -fsSL https://ohmyposh.dev/install.sh | bash -s"
    if [[ ! -d "$HOME/.nvm" ]]; then
        log "Installing NVM..."
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
    else
        log "NVM already installed"
    fi
    if ! command -v cargo &> /dev/null; then
        log "Installing Rust..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    else
        log "Rust already installed"
    fi
    export NVM_DIR="$HOME/.nvm"
    [[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
    command -v nvm &> /dev/null && nvm install 24
    [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
    try_run "claude-code" npm install -g claude-code
}

install_desktop() {
    log "Installing desktop packages..."
    try_run "desktop (pacman)" sudo pacman -S --noconfirm --needed \
        firefox \
        bitwarden \
        alacritty \
        ddccontrol \
        fprintd
    try_run "notion" yay -S --noconfirm --needed notion-app
    try_run "spotify" yay -S --noconfirm --needed spotify
    try_run "ibm-plex-mono" yay -S --noconfirm --needed ttf-ibmplex-mono-nerd
    try_run "atkinson-hyperlegible" yay -S --noconfirm --needed ttf-atkinson-hyperlegible-nerd
}

install_gaming() {
    log "Installing gaming packages..."
    try_run "gaming (pacman)" sudo pacman -S --noconfirm --needed \
        steam
    try_run "discord" yay -S --noconfirm --needed discord
}

install_3d_modelling() {
    log "Installing 3d-modelling packages..."
    try_run "3d-modelling (pacman)" sudo pacman -S --noconfirm --needed \
        blender
}

install_streaming_video_production() {
    log "Installing streaming-video-production packages..."
    try_run "streaming-video-production (pacman)" sudo pacman -S --noconfirm --needed \
        obs-studio
    try_run "da-vinci-resolve" yay -S --noconfirm --needed davinci-resolve
}

install_development() {
    log "Installing development packages..."
    try_run "development (pacman)" sudo pacman -S --noconfirm --needed \
        ansible \
        aws-cli \
        docker \
        go \
        helm \
        kubectl \
        kubectx \
        postgresql \
        python \
        terraform \
        uv \
        bash \
        lua \
        nvtop
    try_run "vscode" yay -S --noconfirm --needed visual-studio-code-bin
}

install_work() {
    log "Installing work packages..."
    try_run "granted" yay -S --noconfirm --needed granted-bin
    try_run "jfrog" yay -S --noconfirm --needed jfrog-cli-bin
}

# ---------------------------------------------------------------------------
# Category selection
# ---------------------------------------------------------------------------
ALL_CATEGORIES=(core desktop gaming 3d-modelling streaming-video-production development work)

selected_categories=("${ALL_CATEGORIES[@]}")

while [[ $# -gt 0 ]]; do
    case "$1" in
        --include)
            IFS=',' read -ra selected_categories <<< "$2"
            shift 2
            ;;
        --exclude)
            IFS=',' read -ra excluded <<< "$2"
            filtered=()
            for cat in "${selected_categories[@]}"; do
                skip=false
                for ex in "${excluded[@]}"; do
                    if [[ "$cat" == "$ex" ]]; then
                        skip=true
                        break
                    fi
                done
                if ! $skip; then
                    filtered+=("$cat")
                fi
            done
            selected_categories=("${filtered[@]}")
            shift 2
            ;;
        *)
            warn "Unknown argument: $1"
            shift
            ;;
    esac
done

log "Selected categories: ${selected_categories[*]}"

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
for cat in "${selected_categories[@]}"; do
    case "$cat" in
        core)
            install_core
            ;;
        desktop)
            install_desktop
            ;;
        gaming)
            install_gaming
            ;;
        3d-modelling)
            install_3d_modelling
            ;;
        streaming-video-production)
            install_streaming_video_production
            ;;
        development)
            install_development
            ;;
        work)
            install_work
            ;;
        *)
            warn "Unknown category: $cat"
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
if [[ ${#FAILED_PACKAGES[@]} -gt 0 ]]; then
    echo "=== Installation completed with errors ==="
    echo "The following packages failed to install:"
    for pkg in "${FAILED_PACKAGES[@]}"; do
        echo "  - $pkg"
    done
    exit 1
else
    echo "=== All packages installed successfully ==="
fi
