#!/bin/bash
# =============================================================================
# GENERATED FILE — DO NOT EDIT
# Generated by scripts/generate.py from packages.yaml
# Re-generate with: python3 scripts/generate.py (or: make generate)
# =============================================================================
set -euo pipefail

# Source OS identification
if [[ -f /etc/os-release ]]; then
    . /etc/os-release
fi

FAILED_PACKAGES=()

log() {
    echo "==> $*"
}

warn() {
    echo "WARNING: $*" >&2
}

try_run() {
    local desc="$1"
    shift
    if ! "$@"; then
        warn "Failed to install: $desc"
        FAILED_PACKAGES+=("$desc")
    fi
}

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------
log "Updating system and installing build prerequisites..."
sudo apt update && sudo apt upgrade -y
sudo apt install -y \
    wget \
    curl \
    git \
    g++ \
    pkg-config \
    libfontconfig1-dev \
    libxcb-xfixes0-dev \
    libxkbcommon-dev

install_core() {
    log "Installing core packages..."
    try_run "core (apt)" sudo apt install -y \
        wget \
        curl \
        git \
        stow \
        zsh \
        tmux \
        jq \
        ripgrep \
        cmake \
        gpg \
        unzip \
        rsync \
        tldr \
        btop \
        fastfetch \
        sipcalc \
        net-tools \
        ttl
    log "Setting up eza repository..."
    curl -fsSL https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
    sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
    sudo apt update
    try_run "eza" sudo apt install -y eza
    log "Installing bitwarden-cli..."
    try_run "bitwarden-cli" bash -c "wget -q https://github.com/bitwarden/clients/releases/download/cli-v2025.5.0/bw-linux-2025.5.0.zip -O /tmp/bitwarden_cli.zip && sudo unzip -o -q /tmp/bitwarden_cli.zip -d /usr/local/bin && rm -f /tmp/bitwarden_cli.zip"
    log "Installing neovim..."
    try_run "neovim" bash -c "curl -sL https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz | sudo tar -xzf - --strip-components=1 --overwrite -C /usr"
    log "Installing fzf..."
    try_run "fzf" bash -c "curl -sL https://github.com/junegunn/fzf/releases/latest/download/fzf-linux_amd64.tar.gz | sudo tar -xzf - -C /usr/local/bin"
    log "Installing oh-my-posh..."
    try_run "oh-my-posh" bash -c "curl -fsSL https://ohmyposh.dev/install.sh | bash -s"
    log "Installing tailscale..."
    try_run "tailscale" bash -c "curl -fsSL https://tailscale.com/install.sh | bash -s"
    if ! command -v cargo &> /dev/null; then
        log "Installing Rust..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    else
        log "Rust already installed"
    fi
    [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
    if [[ ! -d "$HOME/.nvm" ]]; then
        log "Installing NVM..."
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
    else
        log "NVM already installed"
    fi
    export NVM_DIR="$HOME/.nvm"
    [[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
    command -v nvm &> /dev/null && nvm install 24
    try_run "claude-code" npm install -g claude-code
}

install_desktop() {
    log "Installing desktop packages..."
    try_run "desktop (apt)" sudo apt install -y \
        rofi \
        ddccontrol \
        fprintd
    log "Setting up firefox repository..."
    sudo install -d -m 0755 /etc/apt/keyrings
    wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
    echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee /etc/apt/sources.list.d/mozilla.list
    sudo apt update
    try_run "firefox" sudo apt install -y firefox
    log "Setting up spotify repository..."
    curl -sS https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/spotify.gpg
    echo "deb https://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
    sudo apt update
    try_run "spotify" sudo apt install -y spotify-client
    log "Installing bitwarden..."
    try_run "bitwarden" bash -c "wget -q https://github.com/bitwarden/clients/releases/download/desktop-v2025.5.1/Bitwarden-2025.5.1-amd64.deb -O /tmp/bitwarden.deb && sudo dpkg -i /tmp/bitwarden.deb; sudo apt-get install -f -y && rm -f /tmp/bitwarden.deb"
    log "Installing notion..."
    try_run "notion" bash -c "wget -q https://github.com/puneetsl/lotion/releases/download/v1.0.0/lotion_1.0.0_amd64.deb -O /tmp/notion.deb && sudo dpkg -i /tmp/notion.deb; sudo apt-get install -f -y && rm -f /tmp/notion.deb"
    log "Installing ibm-plex-mono font..."
    mkdir -p "$HOME/.local/share/fonts"
    try_run "ibm-plex-mono" bash -c "curl -sL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IBMPlexMono.tar.xz | tar -xJf - -C $HOME/.local/share/fonts"
    fc-cache -fv > /dev/null 2>&1 || true
    log "Installing atkinson-hyperlegible font..."
    mkdir -p "$HOME/.local/share/fonts"
    try_run "atkinson-hyperlegible" bash -c "curl -sL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/AtkinsonHyperlegible.tar.xz | tar -xJf - -C $HOME/.local/share/fonts"
    fc-cache -fv > /dev/null 2>&1 || true
    try_run "alacritty" cargo install alacritty
}

install_gaming() {
    log "Installing gaming packages..."
    try_run "gaming (apt)" sudo apt install -y \
        steam
    log "Installing discord..."
    try_run "discord" bash -c "wget -q https://stable.dl2.discordapp.net/apps/linux/0.0.96/discord-0.0.96.deb -O /tmp/discord.deb && sudo dpkg -i /tmp/discord.deb; sudo apt-get install -f -y && rm -f /tmp/discord.deb"
}

install_3d_modelling() {
    log "Installing 3d-modelling packages..."
    try_run "3d-modelling (apt)" sudo apt install -y \
        blender
}

install_streaming_video_production() {
    log "Installing streaming-video-production packages..."
    try_run "streaming-video-production (apt)" sudo apt install -y \
        obs-studio
}

install_development() {
    log "Installing development packages..."
    try_run "development (apt)" sudo apt install -y \
        ansible \
        docker.io \
        golang \
        postgresql-client \
        python3 \
        lua5.4 \
        nvtop
    log "Setting up helm repository..."
    curl https://baltocdn.com/helm/signing.asc | sudo gpg --dearmor -o /usr/share/keyrings/helm.gpg
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    sudo apt update
    try_run "helm" sudo apt install -y helm
    log "Setting up kubectl repository..."
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    sudo apt update
    try_run "kubectl" sudo apt install -y kubectl
    log "Installing vscode..."
    try_run "vscode" bash -c "wget -q https://vscode.download.prss.microsoft.com/dbazure/download/stable/258e40fedc6cb8edf399a463ce3a9d32e7e1f6f3/code_1.100.3-1748872405_amd64.deb -O /tmp/vscode.deb && sudo dpkg -i /tmp/vscode.deb; sudo apt-get install -f -y && rm -f /tmp/vscode.deb"
    log "Installing uv..."
    try_run "uv" bash -c "curl -fsSL https://astral.sh/uv/install.sh | bash -s"
}

install_work() {
    log "Installing work packages..."
    log "Installing jfrog..."
    try_run "jfrog" bash -c "curl -fsSL https://getcli.jfrog.io | bash -s"
}

# ---------------------------------------------------------------------------
# Category selection
# ---------------------------------------------------------------------------
ALL_CATEGORIES=(core desktop gaming 3d-modelling streaming-video-production development work)

selected_categories=("${ALL_CATEGORIES[@]}")

while [[ $# -gt 0 ]]; do
    case "$1" in
        --include)
            IFS=',' read -ra selected_categories <<< "$2"
            shift 2
            ;;
        --exclude)
            IFS=',' read -ra excluded <<< "$2"
            filtered=()
            for cat in "${selected_categories[@]}"; do
                skip=false
                for ex in "${excluded[@]}"; do
                    if [[ "$cat" == "$ex" ]]; then
                        skip=true
                        break
                    fi
                done
                if ! $skip; then
                    filtered+=("$cat")
                fi
            done
            selected_categories=("${filtered[@]}")
            shift 2
            ;;
        *)
            warn "Unknown argument: $1"
            shift
            ;;
    esac
done

log "Selected categories: ${selected_categories[*]}"

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
for cat in "${selected_categories[@]}"; do
    case "$cat" in
        core)
            install_core
            ;;
        desktop)
            install_desktop
            ;;
        gaming)
            install_gaming
            ;;
        3d-modelling)
            install_3d_modelling
            ;;
        streaming-video-production)
            install_streaming_video_production
            ;;
        development)
            install_development
            ;;
        work)
            install_work
            ;;
        *)
            warn "Unknown category: $cat"
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
if [[ ${#FAILED_PACKAGES[@]} -gt 0 ]]; then
    echo "=== Installation completed with errors ==="
    echo "The following packages failed to install:"
    for pkg in "${FAILED_PACKAGES[@]}"; do
        echo "  - $pkg"
    done
    exit 1
else
    echo "=== All packages installed successfully ==="
fi
