#!/usr/bin/env python3
"""Generate OS-specific install scripts from packages.yaml.

Reads packages.yaml and produces arch.sh, debian-ubuntu.sh, and macos.sh
with category selection support. Generated scripts are committed to git
so install-time has zero Python dependency.
"""

import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

try:
    import yaml
except ImportError:
    print("Error: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

SCRIPT_DIR = Path(__file__).parent
REPO_DIR = SCRIPT_DIR.parent
PACKAGES_YAML = REPO_DIR / "packages.yaml"


@dataclass
class PackageSpec:
    key: str
    category: str
    install_type: str  # default, yay, script, npm, cargo, deb, apt-repo, tap, cask
    pkg_name: str
    url: Optional[str] = None
    setup: Optional[str] = None
    tap: Optional[str] = None
    description: str = ""


def load_packages() -> dict:
    with open(PACKAGES_YAML) as f:
        return yaml.safe_load(f)


def resolve_spec(key: str, category: str, raw, os_key: str) -> Optional[PackageSpec]:
    """Resolve a single package's OS entry into a PackageSpec."""
    if raw is None:
        # ~ or null means default package manager, name = key
        return PackageSpec(key=key, category=category, install_type="default", pkg_name=key)
    if isinstance(raw, str):
        # bare string means default package manager, custom name
        return PackageSpec(key=key, category=category, install_type="default", pkg_name=raw)
    if isinstance(raw, dict):
        install_type = raw.get("type", "default")
        # Normalize platform-specific aliases to "default"
        if install_type == "apt":
            install_type = "default"
        pkg_name = raw.get("name", key)
        url = raw.get("url")
        setup = raw.get("setup")
        tap = raw.get("tap")
        return PackageSpec(
            key=key, category=category, install_type=install_type,
            pkg_name=pkg_name, url=url, setup=setup, tap=tap,
        )
    return None


def resolve_os(data: dict, os_key: str) -> dict[str, list[PackageSpec]]:
    """Resolve all packages for a given OS key. Returns {category: [specs]}."""
    categories: dict[str, list[PackageSpec]] = {}
    for category, packages in data.items():
        specs = []
        for key, pkg_data in packages.items():
            if os_key not in pkg_data:
                continue
            spec = resolve_spec(key, category, pkg_data[os_key], os_key)
            if spec:
                spec.description = pkg_data.get("description", "")
                specs.append(spec)
        if specs:
            categories[category] = specs
    return categories


def func_name(category: str) -> str:
    """Convert category name to bash function name."""
    return "install_" + category.replace("-", "_")


def dedup(items: list[str]) -> list[str]:
    """Remove duplicates while preserving order."""
    seen: set[str] = set()
    result = []
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result


# ---------------------------------------------------------------------------
# Shared templates
# ---------------------------------------------------------------------------

HEADER = """\
#!/bin/bash
# =============================================================================
# GENERATED FILE — DO NOT EDIT
# Generated by scripts/generate.py from packages.yaml
# Re-generate with: python3 scripts/generate.py (or: make generate)
# =============================================================================
set -euo pipefail
"""

HELPERS = """\
FAILED_PACKAGES=()

log() {
    echo "==> $*"
}

warn() {
    echo "WARNING: $*" >&2
}

try_run() {
    local desc="$1"
    shift
    if ! "$@"; then
        warn "Failed to install: $desc"
        FAILED_PACKAGES+=("$desc")
    fi
}
"""

CATEGORY_SELECTOR = """\
# ---------------------------------------------------------------------------
# Category selection
# ---------------------------------------------------------------------------
ALL_CATEGORIES=({categories})

selected_categories=("${{ALL_CATEGORIES[@]}}")

while [[ $# -gt 0 ]]; do
    case "$1" in
        --include)
            IFS=',' read -ra selected_categories <<< "$2"
            shift 2
            ;;
        --exclude)
            IFS=',' read -ra excluded <<< "$2"
            filtered=()
            for cat in "${{selected_categories[@]}}"; do
                skip=false
                for ex in "${{excluded[@]}}"; do
                    if [[ "$cat" == "$ex" ]]; then
                        skip=true
                        break
                    fi
                done
                if ! $skip; then
                    filtered+=("$cat")
                fi
            done
            selected_categories=("${{filtered[@]}}")
            shift 2
            ;;
        *)
            warn "Unknown argument: $1"
            shift
            ;;
    esac
done

log "Selected categories: ${{selected_categories[*]}}"
"""

MAIN_LOOP = """\
# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
for cat in "${{selected_categories[@]}}"; do
    case "$cat" in
{cases}
        *)
            warn "Unknown category: $cat"
            ;;
    esac
done
"""

SUMMARY = """\
# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
if [[ ${#FAILED_PACKAGES[@]} -gt 0 ]]; then
    echo "=== Installation completed with errors ==="
    echo "The following packages failed to install:"
    for pkg in "${FAILED_PACKAGES[@]}"; do
        echo "  - $pkg"
    done
    exit 1
else
    echo "=== All packages installed successfully ==="
fi
"""


# ---------------------------------------------------------------------------
# Arch emitter
# ---------------------------------------------------------------------------

def emit_arch(categories: dict[str, list[PackageSpec]]) -> str:
    parts = [HEADER, HELPERS]

    # Prerequisites
    parts.append(textwrap.dedent("""\
        # ---------------------------------------------------------------------------
        # Prerequisites
        # ---------------------------------------------------------------------------
        log "Updating system..."
        sudo pacman -Syu --noconfirm

        if ! command -v yay &> /dev/null; then
            log "Installing yay..."
            sudo pacman -S --noconfirm --needed git base-devel
            tmpdir="$(mktemp -d)"
            git clone https://aur.archlinux.org/yay.git "$tmpdir/yay"
            (cd "$tmpdir/yay" && makepkg -si --noconfirm)
            rm -rf "$tmpdir"
        fi
    """))

    # Category functions
    for category, specs in categories.items():
        fn = func_name(category)
        lines = [f'{fn}() {{', f'    log "Installing {category} packages..."']

        # Phase 0: default (pacman) — batched
        default_pkgs = dedup([s.pkg_name for s in specs if s.install_type == "default"])
        if default_pkgs:
            pkg_list = " \\\n        ".join(default_pkgs)
            lines.append(f'    try_run "{category} (pacman)" sudo pacman -S --noconfirm --needed \\')
            lines.append(f'        {pkg_list}')

        # Phase 2: yay packages
        yay_pkgs = [s for s in specs if s.install_type == "yay"]
        for s in yay_pkgs:
            lines.append(f'    try_run "{s.key}" yay -S --noconfirm --needed {s.pkg_name}')

        # Phase 4: script installs
        script_pkgs = [s for s in specs if s.install_type == "script"]
        for s in script_pkgs:
            lines.extend(_script_install_lines(s, indent=4))

        # Phase 5: toolchain (rust, nvm)
        toolchain_pkgs = [s for s in specs if s.key in ("rust", "nvm") and s.install_type == "script"]
        # Already emitted in script phase above — but we need env sourcing after.
        # Add env sourcing for toolchains only if they appeared
        for s in specs:
            if s.key == "rust" and s.install_type == "script":
                lines.append('    [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"')
            if s.key == "nvm" and s.install_type == "script":
                lines.append('    export NVM_DIR="$HOME/.nvm"')
                lines.append('    [[ -s "$NVM_DIR/nvm.sh" ]] && \\. "$NVM_DIR/nvm.sh"')
                lines.append('    command -v nvm &> /dev/null && nvm install 24')

        # Phase 6: toolchain-dependent (cargo, npm)
        cargo_pkgs = [s for s in specs if s.install_type == "cargo"]
        for s in cargo_pkgs:
            lines.append(f'    try_run "{s.key}" cargo install {s.pkg_name}')

        npm_pkgs = [s for s in specs if s.install_type == "npm"]
        for s in npm_pkgs:
            lines.append(f'    try_run "{s.key}" npm install -g {s.pkg_name}')

        lines.append("}")
        lines.append("")
        parts.append("\n".join(lines))

    # Category selector
    cat_list = " ".join(categories.keys())
    parts.append(CATEGORY_SELECTOR.format(categories=cat_list))

    # Main loop
    cases = ""
    for category in categories:
        fn = func_name(category)
        cases += f'        {category})\n            {fn}\n            ;;\n'
    parts.append(MAIN_LOOP.format(cases=cases.rstrip()))

    parts.append(SUMMARY)
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# macOS emitter
# ---------------------------------------------------------------------------

def emit_macos(categories: dict[str, list[PackageSpec]]) -> str:
    parts = [HEADER, HELPERS]

    # Prerequisites: Homebrew
    parts.append(textwrap.dedent("""\
        # ---------------------------------------------------------------------------
        # Prerequisites
        # ---------------------------------------------------------------------------
        if ! command -v brew &> /dev/null; then
            log "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            if [[ -f "/opt/homebrew/bin/brew" ]]; then
                eval "$(/opt/homebrew/bin/brew shellenv)"
            elif [[ -f "/usr/local/bin/brew" ]]; then
                eval "$(/usr/local/bin/brew shellenv)"
            fi
        fi

        log "Updating Homebrew..."
        brew update
    """))

    # Category functions
    for category, specs in categories.items():
        fn = func_name(category)
        lines = [f'{fn}() {{', f'    log "Installing {category} packages..."']

        # Phase 0: default (brew) — batched
        default_pkgs = dedup([s.pkg_name for s in specs if s.install_type == "default"])
        if default_pkgs:
            pkg_list = " \\\n        ".join(default_pkgs)
            lines.append(f'    try_run "{category} (brew)" brew install \\')
            lines.append(f'        {pkg_list}')

        # Phase 7: cask — batched
        cask_pkgs = [s for s in specs if s.install_type == "cask"]
        if cask_pkgs:
            cask_names = dedup([s.pkg_name for s in cask_pkgs])
            pkg_list = " \\\n        ".join(cask_names)
            lines.append(f'    try_run "{category} (cask)" brew install --cask \\')
            lines.append(f'        {pkg_list}')

        # Phase 8: tap installs
        tap_pkgs = [s for s in specs if s.install_type == "tap"]
        for s in tap_pkgs:
            lines.append(f'    try_run "{s.key} (tap)" bash -c "brew tap {s.tap} && brew install {s.pkg_name}"')

        # Phase 4: script installs
        script_pkgs = [s for s in specs if s.install_type == "script"]
        for s in script_pkgs:
            lines.extend(_script_install_lines(s, indent=4))

        # Toolchain env sourcing
        for s in specs:
            if s.key == "rust" and s.install_type == "script":
                lines.append('    [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"')
            if s.key == "nvm" and s.install_type == "script":
                lines.append('    export NVM_DIR="$HOME/.nvm"')
                lines.append('    [[ -s "$NVM_DIR/nvm.sh" ]] && \\. "$NVM_DIR/nvm.sh"')
                lines.append('    command -v nvm &> /dev/null && nvm install 24')

        # Phase 6: toolchain-dependent
        cargo_pkgs = [s for s in specs if s.install_type == "cargo"]
        for s in cargo_pkgs:
            lines.append(f'    try_run "{s.key}" cargo install {s.pkg_name}')

        npm_pkgs = [s for s in specs if s.install_type == "npm"]
        for s in npm_pkgs:
            lines.append(f'    try_run "{s.key}" npm install -g {s.pkg_name}')

        lines.append("}")
        lines.append("")
        parts.append("\n".join(lines))

    # Category selector
    cat_list = " ".join(categories.keys())
    parts.append(CATEGORY_SELECTOR.format(categories=cat_list))

    # Main loop
    cases = ""
    for category in categories:
        fn = func_name(category)
        cases += f'        {category})\n            {fn}\n            ;;\n'
    parts.append(MAIN_LOOP.format(cases=cases.rstrip()))

    # Change default shell to zsh
    parts.append(textwrap.dedent("""\
        # ---------------------------------------------------------------------------
        # Post-install
        # ---------------------------------------------------------------------------
        if [[ "$SHELL" != "$(which zsh)" ]]; then
            log "Setting zsh as default shell..."
            sudo chsh -s "$(which zsh)" "$USER"
            echo "Shell changed. You may need to log out and back in."
        fi
    """))

    parts.append(SUMMARY)
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Debian/Ubuntu emitter
# ---------------------------------------------------------------------------

def emit_debian_ubuntu() -> str:
    parts = [HEADER]

    # Source /etc/os-release for debian vs ubuntu branching
    parts.append(textwrap.dedent("""\
        # Source OS identification
        if [[ -f /etc/os-release ]]; then
            . /etc/os-release
        fi
    """))

    parts.append(HELPERS)

    # Prerequisites: build tools
    parts.append(textwrap.dedent("""\
        # ---------------------------------------------------------------------------
        # Prerequisites
        # ---------------------------------------------------------------------------
        log "Updating system and installing build prerequisites..."
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y \\
            wget \\
            curl \\
            git \\
            g++ \\
            pkg-config \\
            libfontconfig1-dev \\
            libxcb-xfixes0-dev \\
            libxkbcommon-dev
    """))

    # We need to handle debian/ubuntu branching. For each package, check if
    # debian and ubuntu specs differ — if so, emit a runtime branch.
    # First resolve both.
    data = load_packages()
    deb_categories = resolve_os(data, "debian")
    ubu_categories = resolve_os(data, "ubuntu")

    # Merge category names from both
    all_cats = list(dict.fromkeys(list(deb_categories.keys()) + list(ubu_categories.keys())))

    for category in all_cats:
        fn = func_name(category)
        deb_specs = {s.key: s for s in deb_categories.get(category, [])}
        ubu_specs = {s.key: s for s in ubu_categories.get(category, [])}
        all_keys = list(dict.fromkeys(list(deb_specs.keys()) + list(ubu_specs.keys())))

        lines = [f'{fn}() {{', f'    log "Installing {category} packages..."']

        # Collect packages by phase, handling debian/ubuntu differences
        # Phase 0: default (apt) — batched
        # Collect shared and os-specific default packages
        shared_default = []
        deb_only_default = []
        ubu_only_default = []
        for key in all_keys:
            d = deb_specs.get(key)
            u = ubu_specs.get(key)
            if d and u and d.install_type == "default" and u.install_type == "default":
                if d.pkg_name == u.pkg_name:
                    shared_default.append(d.pkg_name)
                else:
                    deb_only_default.append(d.pkg_name)
                    ubu_only_default.append(u.pkg_name)
            elif d and d.install_type == "default" and not u:
                deb_only_default.append(d.pkg_name)
            elif u and u.install_type == "default" and not d:
                ubu_only_default.append(u.pkg_name)

        shared_default = dedup(shared_default)
        deb_only_default = dedup(deb_only_default)
        ubu_only_default = dedup(ubu_only_default)

        if shared_default:
            pkg_list = " \\\n        ".join(shared_default)
            lines.append(f'    try_run "{category} (apt)" sudo apt install -y \\')
            lines.append(f'        {pkg_list}')

        if deb_only_default or ubu_only_default:
            if deb_only_default:
                pkg_list = " ".join(deb_only_default)
                lines.append(f'    if [[ "${{ID:-}}" != "ubuntu" ]]; then')
                lines.append(f'        try_run "{category} (apt/debian)" sudo apt install -y {pkg_list}')
                lines.append(f'    fi')
            if ubu_only_default:
                pkg_list = " ".join(ubu_only_default)
                lines.append(f'    if [[ "${{ID:-}}" == "ubuntu" ]]; then')
                lines.append(f'        try_run "{category} (apt/ubuntu)" sudo apt install -y {pkg_list}')
                lines.append(f'    fi')

        # Phase 1: apt-repo setups
        for key in all_keys:
            d = deb_specs.get(key)
            u = ubu_specs.get(key)
            # Use debian spec as primary (they're usually identical)
            spec = d or u
            if not spec or spec.install_type != "apt-repo":
                continue
            lines.append(f'    log "Setting up {spec.key} repository..."')
            if spec.setup:
                for setup_line in spec.setup.strip().splitlines():
                    lines.append(f'    {setup_line}')
            apt_name = spec.pkg_name
            lines.append(f'    try_run "{spec.key}" sudo apt install -y {apt_name}')

        # Phase 3: deb/zip downloads
        for key in all_keys:
            d = deb_specs.get(key)
            u = ubu_specs.get(key)
            spec = d or u
            if not spec or spec.install_type != "deb":
                continue
            lines.extend(_deb_install_lines(spec, indent=4))

        # Phase 4: script installs (non-toolchain)
        for key in all_keys:
            d = deb_specs.get(key)
            u = ubu_specs.get(key)
            spec = d or u
            if not spec or spec.install_type != "script":
                continue
            if spec.key in ("rust", "nvm"):
                continue  # handled in toolchain phase
            lines.extend(_script_install_lines(spec, indent=4))

        # Phase 5: toolchain installs
        for key in ("rust", "nvm"):
            d = deb_specs.get(key)
            u = ubu_specs.get(key)
            spec = d or u
            if not spec or spec.install_type != "script":
                continue
            lines.extend(_script_install_lines(spec, indent=4))
            if key == "rust":
                lines.append('    [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"')
            if key == "nvm":
                lines.append('    export NVM_DIR="$HOME/.nvm"')
                lines.append('    [[ -s "$NVM_DIR/nvm.sh" ]] && \\. "$NVM_DIR/nvm.sh"')
                lines.append('    command -v nvm &> /dev/null && nvm install 24')

        # Phase 6: toolchain-dependent (cargo, npm)
        for key in all_keys:
            d = deb_specs.get(key)
            u = ubu_specs.get(key)
            spec = d or u
            if not spec:
                continue
            if spec.install_type == "cargo":
                lines.append(f'    try_run "{spec.key}" cargo install {spec.pkg_name}')
            elif spec.install_type == "npm":
                lines.append(f'    try_run "{spec.key}" npm install -g {spec.pkg_name}')

        lines.append("}")
        lines.append("")
        parts.append("\n".join(lines))

    # Category selector
    cat_list = " ".join(all_cats)
    parts.append(CATEGORY_SELECTOR.format(categories=cat_list))

    # Main loop
    cases = ""
    for category in all_cats:
        fn = func_name(category)
        cases += f'        {category})\n            {fn}\n            ;;\n'
    parts.append(MAIN_LOOP.format(cases=cases.rstrip()))

    parts.append(SUMMARY)
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Script install helpers
# ---------------------------------------------------------------------------

def _script_install_lines(spec: PackageSpec, indent: int = 4) -> list[str]:
    """Return shell lines for a script-type install."""
    pad = " " * indent
    lines = []
    url = spec.url or ""

    if spec.key == "rust":
        lines.append(f'{pad}if ! command -v cargo &> /dev/null; then')
        lines.append(f'{pad}    log "Installing Rust..."')
        lines.append(f'{pad}    curl --proto \'=https\' --tlsv1.2 -sSf {url} | sh -s -- -y')
        lines.append(f'{pad}else')
        lines.append(f'{pad}    log "Rust already installed"')
        lines.append(f'{pad}fi')
    elif spec.key == "nvm":
        lines.append(f'{pad}if [[ ! -d "$HOME/.nvm" ]]; then')
        lines.append(f'{pad}    log "Installing NVM..."')
        lines.append(f'{pad}    curl -o- {url} | bash')
        lines.append(f'{pad}else')
        lines.append(f'{pad}    log "NVM already installed"')
        lines.append(f'{pad}fi')
    elif spec.key == "neovim":
        # tarball extract to /usr
        lines.append(f'{pad}log "Installing {spec.key}..."')
        lines.append(f'{pad}try_run "{spec.key}" bash -c "curl -sL {url} | sudo tar -xzf - --strip-components=1 --overwrite -C /usr"')
    elif spec.key == "fzf":
        # tarball extract to /usr/local/bin
        lines.append(f'{pad}log "Installing {spec.key}..."')
        lines.append(f'{pad}try_run "{spec.key}" bash -c "curl -sL {url} | sudo tar -xzf - -C /usr/local/bin"')
    elif _is_font_url(url):
        # Font archive: extract to ~/.local/share/fonts
        font_dir = "$HOME/.local/share/fonts"
        lines.append(f'{pad}log "Installing {spec.key} font..."')
        lines.append(f'{pad}mkdir -p "{font_dir}"')
        lines.append(f'{pad}try_run "{spec.key}" bash -c "curl -sL {url} | tar -xJf - -C {font_dir}"')
        lines.append(f'{pad}fc-cache -fv > /dev/null 2>&1 || true')
    elif url.endswith(".tar.gz") or url.endswith(".tar.xz"):
        # Generic tarball
        lines.append(f'{pad}log "Installing {spec.key}..."')
        lines.append(f'{pad}try_run "{spec.key}" bash -c "curl -sL {url} | sudo tar -xzf - -C /usr/local/bin"')
    else:
        # pipe to bash
        lines.append(f'{pad}log "Installing {spec.key}..."')
        lines.append(f'{pad}try_run "{spec.key}" bash -c "curl -fsSL {url} | bash -s"')

    return lines


def _is_font_url(url: str) -> bool:
    """Check if URL looks like a Nerd Font release archive."""
    return "nerd-fonts/releases" in url


def _deb_install_lines(spec: PackageSpec, indent: int = 4) -> list[str]:
    """Return shell lines for a deb/zip install."""
    pad = " " * indent
    lines = []
    url = spec.url or ""
    tmp_name = spec.key.replace("-", "_")

    if url.endswith(".zip"):
        # ZIP archive (e.g., bitwarden-cli)
        lines.append(f'{pad}log "Installing {spec.key}..."')
        lines.append(f'{pad}try_run "{spec.key}" bash -c "wget -q {url} -O /tmp/{tmp_name}.zip && sudo unzip -o -q /tmp/{tmp_name}.zip -d /usr/local/bin && rm -f /tmp/{tmp_name}.zip"')
    else:
        # .deb package
        lines.append(f'{pad}log "Installing {spec.key}..."')
        lines.append(f'{pad}try_run "{spec.key}" bash -c "wget -q {url} -O /tmp/{tmp_name}.deb && sudo dpkg -i /tmp/{tmp_name}.deb; sudo apt-get install -f -y && rm -f /tmp/{tmp_name}.deb"')

    return lines


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    data = load_packages()

    # Resolve per-OS
    arch_cats = resolve_os(data, "arch")
    macos_cats = resolve_os(data, "macos")

    # Generate scripts
    arch_script = emit_arch(arch_cats)
    macos_script = emit_macos(macos_cats)
    debian_script = emit_debian_ubuntu()

    # Write output
    for name, content in [
        ("arch.sh", arch_script),
        ("macos.sh", macos_script),
        ("debian-ubuntu.sh", debian_script),
    ]:
        path = SCRIPT_DIR / name
        path.write_text(content)
        path.chmod(0o755)
        print(f"Generated {path}")

    print("Done.")


if __name__ == "__main__":
    main()
