#!/bin/bash
# =============================================================================
# GENERATED FILE — DO NOT EDIT
# Generated by scripts/generate.py from packages.yaml
# Re-generate with: python3 scripts/generate.py (or: make generate)
# =============================================================================
set -euo pipefail

FAILED_PACKAGES=()

log() {
    echo "==> $*"
}

warn() {
    echo "WARNING: $*" >&2
}

try_run() {
    local desc="$1"
    shift
    if ! "$@"; then
        warn "Failed to install: $desc"
        FAILED_PACKAGES+=("$desc")
    fi
}

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------
if ! command -v brew &> /dev/null; then
    log "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    if [[ -f "/opt/homebrew/bin/brew" ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -f "/usr/local/bin/brew" ]]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

log "Updating Homebrew..."
brew update

install_core() {
    log "Installing core packages..."
    try_run "core (brew)" brew install \
        wget \
        curl \
        git \
        stow \
        zsh \
        tmux \
        neovim \
        jq \
        yq \
        ripgrep \
        grex \
        fzf \
        cmake \
        gnupg \
        unzip \
        rsync \
        tldr \
        btop \
        fastfetch \
        sipcalc \
        ttl \
        bitwarden-cli \
        eza
    try_run "core (cask)" brew install --cask \
        tailscale
    try_run "oh-my-posh (tap)" bash -c "brew tap jandedobbeleer/oh-my-posh && brew install oh-my-posh"
    if [[ ! -d "$HOME/.nvm" ]]; then
        log "Installing NVM..."
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
    else
        log "NVM already installed"
    fi
    if ! command -v cargo &> /dev/null; then
        log "Installing Rust..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    else
        log "Rust already installed"
    fi
    export NVM_DIR="$HOME/.nvm"
    [[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
    command -v nvm &> /dev/null && nvm install 24
    [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
    try_run "claude-code" npm install -g claude-code
}

install_desktop() {
    log "Installing desktop packages..."
    try_run "desktop (cask)" brew install --cask \
        firefox \
        bitwarden \
        notion \
        spotify \
        alacritty \
        raycast \
        font-ibm-plex-mono-nerd-font \
        font-atkinson-hyperlegible-nerd-font
}

install_gaming() {
    log "Installing gaming packages..."
    try_run "gaming (cask)" brew install --cask \
        discord
}

install_3d_modelling() {
    log "Installing 3d-modelling packages..."
    try_run "3d-modelling (cask)" brew install --cask \
        blender
}

install_streaming_video_production() {
    log "Installing streaming-video-production packages..."
    try_run "streaming-video-production (cask)" brew install --cask \
        obs
}

install_development() {
    log "Installing development packages..."
    try_run "development (brew)" brew install \
        ansible \
        awscli \
        go \
        helm \
        kubectl \
        kubectx \
        postgresql@16 \
        python@3.12 \
        terraform \
        uv \
        bash \
        lua
    try_run "development (cask)" brew install --cask \
        docker \
        visual-studio-code
}

install_work() {
    log "Installing work packages..."
    try_run "granted (tap)" bash -c "brew tap common-fate/granted && brew install granted"
    try_run "jfrog (tap)" bash -c "brew tap jfrog/tap && brew install jfrog-cli"
}

# ---------------------------------------------------------------------------
# Category selection
# ---------------------------------------------------------------------------
ALL_CATEGORIES=(core desktop gaming 3d-modelling streaming-video-production development work)

selected_categories=("${ALL_CATEGORIES[@]}")

while [[ $# -gt 0 ]]; do
    case "$1" in
        --include)
            IFS=',' read -ra selected_categories <<< "$2"
            shift 2
            ;;
        --exclude)
            IFS=',' read -ra excluded <<< "$2"
            filtered=()
            for cat in "${selected_categories[@]}"; do
                skip=false
                for ex in "${excluded[@]}"; do
                    if [[ "$cat" == "$ex" ]]; then
                        skip=true
                        break
                    fi
                done
                if ! $skip; then
                    filtered+=("$cat")
                fi
            done
            selected_categories=("${filtered[@]}")
            shift 2
            ;;
        *)
            warn "Unknown argument: $1"
            shift
            ;;
    esac
done

log "Selected categories: ${selected_categories[*]}"

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
for cat in "${selected_categories[@]}"; do
    case "$cat" in
        core)
            install_core
            ;;
        desktop)
            install_desktop
            ;;
        gaming)
            install_gaming
            ;;
        3d-modelling)
            install_3d_modelling
            ;;
        streaming-video-production)
            install_streaming_video_production
            ;;
        development)
            install_development
            ;;
        work)
            install_work
            ;;
        *)
            warn "Unknown category: $cat"
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Post-install
# ---------------------------------------------------------------------------
if [[ "$SHELL" != "$(which zsh)" ]]; then
    log "Setting zsh as default shell..."
    sudo chsh -s "$(which zsh)" "$USER"
    echo "Shell changed. You may need to log out and back in."
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
if [[ ${#FAILED_PACKAGES[@]} -gt 0 ]]; then
    echo "=== Installation completed with errors ==="
    echo "The following packages failed to install:"
    for pkg in "${FAILED_PACKAGES[@]}"; do
        echo "  - $pkg"
    done
    exit 1
else
    echo "=== All packages installed successfully ==="
fi
