# Arch Linux (Omarchy) Alacritty overrides

[general]
import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[window]
decorations = "None"
padding = { x = 14, y = 14 }

[font]
size = 9

[keyboard]
bindings = [
    { key = "Insert", mods = "Shift", action = "Paste" },
    { key = "Insert", mods = "Control", action = "Copy" },
    { key = "Return", mods = "Shift", chars = "\u001B\r" },
]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
mouse = { enabled = true, mods = "Shift" }
command = "xdg-open"
