# macOS-specific Alacritty overrides

[window]
decorations = "Full"

[font]
size = 20

[keyboard]
bindings = [
    { key = "Insert", mods = "Shift", action = "Paste" },
    { key = "Insert", mods = "Control", action = "Copy" },
    { key = "Return", mods = "Shift", chars = "\u001B\r" },
    { key = "Left", mods = "Command", action = "WordLeft" },
    { key = "Right", mods = "Command", action = "WordRight" },
    { key = "Backspace", mods = "Command", chars = "\u0017" },
    { key = "Delete", mods = "Command", chars = "\u001Bd" },
]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
mouse = { enabled = true, mods = "Shift" }
command = "open"
