name: test

on:
  pull_request:
    branches: [main]

jobs:
  make-test:
    name: test (${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: debian
            runner: ubuntu-latest
            command: python3 test/run_tests.py debian
          - target: ubuntu
            runner: ubuntu-latest
            command: python3 test/run_tests.py ubuntu
          - target: arch
            runner: ubuntu-latest
            command: python3 test/run_tests.py arch
          - target: macos
            runner: macos-latest
            command: ./install.sh --yes --skip-stow --include core
    steps:
      - uses: actions/checkout@v4
      - name: Run test for ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${{ matrix.command }}
