name: test

on:
  pull_request:
    branches: [main]

jobs:
  make-test:
    name: test (${{ matrix.distro }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [debian, ubuntu, arch]
    steps:
      - uses: actions/checkout@v4
      - name: Run test for ${{ matrix.distro }}
        run: python3 test/run_tests.py ${{ matrix.distro }}
